### ISSUE TITLE
parse-long already being referred to from Clojure 1.11.0 onwards.

### ISSUE THREAD

**Issue by dharrigan** [doubleagent/gooff#1]
Hi!

Great library, just one thing I've come across recently. With newer versions of Clojure (from 1.11.0 onwards), `parse-long` is already provided. Would it be possible to cut another release that targets Clojure 1.11.0 onwards please, or perhaps rename `parse-long` to an internal name?

Here is the warning:

```
WARNING: parse-long already refers to: #'clojure.core/parse-long in namespace: gooff.core, being replaced by: #'gooff.core/parse-long
```

Thank you very much.

-=david=-

**Comment by crinklywrappr** [comment]
Glad you're enjoying it!

It may be a while before I can get around to this, but I am happy to review a pull request. 🙂
